insight-ltc-testnet:
    build: .
    dockerfile: Dockerfile
    container_name: insight-ltc-testnet
    ports:
      - "4002:3001"   # API endpoint
      #- "28331:28331" # ZMQ port
    volumes:
      - ./data_ltc_mainnet:/mynode/data
    restart: always